package com.example.acceptance.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.acceptance.greendao.bean.CheckGroupBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHECK_GROUP_BEAN".
*/
public class CheckGroupBeanDao extends AbstractDao<CheckGroupBean, Long> {

    public static final String TABLENAME = "CHECK_GROUP_BEAN";

    /**
     * Properties of entity CheckGroupBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UId = new Property(0, Long.class, "uId", true, "_id");
        public final static Property DataPackageId = new Property(1, String.class, "dataPackageId", false, "DATA_PACKAGE_ID");
        public final static Property CheckFileId = new Property(2, String.class, "checkFileId", false, "CHECK_FILE_ID");
        public final static Property Id = new Property(3, String.class, "id", false, "ID");
        public final static Property GroupName = new Property(4, String.class, "groupName", false, "GROUP_NAME");
        public final static Property CheckGroupConclusion = new Property(5, String.class, "checkGroupConclusion", false, "CHECK_GROUP_CONCLUSION");
        public final static Property CheckPerson = new Property(6, String.class, "checkPerson", false, "CHECK_PERSON");
        public final static Property IsConclusion = new Property(7, String.class, "isConclusion", false, "IS_CONCLUSION");
        public final static Property IsTable = new Property(8, String.class, "isTable", false, "IS_TABLE");
    }


    public CheckGroupBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CheckGroupBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHECK_GROUP_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: uId
                "\"DATA_PACKAGE_ID\" TEXT," + // 1: dataPackageId
                "\"CHECK_FILE_ID\" TEXT," + // 2: checkFileId
                "\"ID\" TEXT," + // 3: id
                "\"GROUP_NAME\" TEXT," + // 4: groupName
                "\"CHECK_GROUP_CONCLUSION\" TEXT," + // 5: checkGroupConclusion
                "\"CHECK_PERSON\" TEXT," + // 6: checkPerson
                "\"IS_CONCLUSION\" TEXT," + // 7: isConclusion
                "\"IS_TABLE\" TEXT);"); // 8: isTable
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHECK_GROUP_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CheckGroupBean entity) {
        stmt.clearBindings();
 
        Long uId = entity.getUId();
        if (uId != null) {
            stmt.bindLong(1, uId);
        }
 
        String dataPackageId = entity.getDataPackageId();
        if (dataPackageId != null) {
            stmt.bindString(2, dataPackageId);
        }
 
        String checkFileId = entity.getCheckFileId();
        if (checkFileId != null) {
            stmt.bindString(3, checkFileId);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(4, id);
        }
 
        String groupName = entity.getGroupName();
        if (groupName != null) {
            stmt.bindString(5, groupName);
        }
 
        String checkGroupConclusion = entity.getCheckGroupConclusion();
        if (checkGroupConclusion != null) {
            stmt.bindString(6, checkGroupConclusion);
        }
 
        String checkPerson = entity.getCheckPerson();
        if (checkPerson != null) {
            stmt.bindString(7, checkPerson);
        }
 
        String isConclusion = entity.getIsConclusion();
        if (isConclusion != null) {
            stmt.bindString(8, isConclusion);
        }
 
        String isTable = entity.getIsTable();
        if (isTable != null) {
            stmt.bindString(9, isTable);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CheckGroupBean entity) {
        stmt.clearBindings();
 
        Long uId = entity.getUId();
        if (uId != null) {
            stmt.bindLong(1, uId);
        }
 
        String dataPackageId = entity.getDataPackageId();
        if (dataPackageId != null) {
            stmt.bindString(2, dataPackageId);
        }
 
        String checkFileId = entity.getCheckFileId();
        if (checkFileId != null) {
            stmt.bindString(3, checkFileId);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(4, id);
        }
 
        String groupName = entity.getGroupName();
        if (groupName != null) {
            stmt.bindString(5, groupName);
        }
 
        String checkGroupConclusion = entity.getCheckGroupConclusion();
        if (checkGroupConclusion != null) {
            stmt.bindString(6, checkGroupConclusion);
        }
 
        String checkPerson = entity.getCheckPerson();
        if (checkPerson != null) {
            stmt.bindString(7, checkPerson);
        }
 
        String isConclusion = entity.getIsConclusion();
        if (isConclusion != null) {
            stmt.bindString(8, isConclusion);
        }
 
        String isTable = entity.getIsTable();
        if (isTable != null) {
            stmt.bindString(9, isTable);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CheckGroupBean readEntity(Cursor cursor, int offset) {
        CheckGroupBean entity = new CheckGroupBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // uId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // dataPackageId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // checkFileId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // groupName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // checkGroupConclusion
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // checkPerson
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // isConclusion
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // isTable
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CheckGroupBean entity, int offset) {
        entity.setUId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDataPackageId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCheckFileId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGroupName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCheckGroupConclusion(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCheckPerson(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsConclusion(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIsTable(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CheckGroupBean entity, long rowId) {
        entity.setUId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CheckGroupBean entity) {
        if(entity != null) {
            return entity.getUId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CheckGroupBean entity) {
        return entity.getUId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
